name: mnstrv2
description: "A new adventure awaits!"
publish_to: 'none'
version: 2.18.0+104

environment:
  sdk: ^3.12.1
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  mobile_scanner: ^7.2.0
  crypto: ^3.0.7
  screenshot: ^3.0.0
  http: ^1.6.0
  share_plus: ^13.1.0
  flutter_riverpod: ^3.3.1
  json_serializable: ^6.14.0
  json_annotation: ^4.12.0
  uuid: ^4.5.3
  riverpod: ^3.2.1
  shared_preferences: ^2.5.5
  flutter_launcher_icons: ^0.14.4
  just_audio: ^0.10.5
  audioplayers: ^6.7.1
  flame_audio: ^2.12.1
  change_case: ^2.2.0
  motor: ^1.1.0
  web_socket_channel: ^3.0.3
  platform: ^3.1.6
  universal_platform: ^1.1.0
  material_symbols_icons: ^4.2928.1
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.1
  yaml: ^3.1.3
  hive: ^2.2.3
  path_provider: ^2.1.5
  sqflite: ^2.4.3
  sqflite_common: ^2.5.9
  sqflite_common_ffi: ^2.4.1
  sqflite_common_ffi_web: ^1.1.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/mnstr_parts/
    - assets/items/
    - assets/stars/
    - assets/audio/
    - assets/environment/
  fonts:
    - family: Pixelify
      fonts:
        - asset: assets/fonts/PixelifySans-VariableFont_wght.ttf

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#00f0ff"
  adaptive_icon_foreground: "assets/logo.png"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#00f0ff"
    theme_color: "#00f0ff"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"