name: mnstrv2
description: "A new adventure awaits!"
publish_to: "none"
version: 2.11.0+28

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.0.1
  crypto: ^3.0.6
  screenshot: ^3.0.0
  http: ^1.4.0
  share_plus: ^11.0.0
  flutter_riverpod: ^2.6.1
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4
  just_audio: ^0.10.4
  audioplayers: ^6.5.0
  flame_audio: ^2.11.8
  change_case: ^2.2.0
  motor: ^1.0.1
  web_socket_channel: ^3.0.3
  platform: ^3.1.6
  universal_platform: ^1.1.0
  material_symbols_icons: ^4.2874.0
  wiredash: ^2.5.0
  dotenv: ^4.2.0
  flutter_dotenv: ^6.0.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/mnstr_parts/
    - assets/items/
    - assets/stars/
    - assets/audio/
  fonts:
    - family: Silkscreen
      fonts:
        - asset: assets/fonts/Silkscreen-Regular.ttf
        - asset: assets/fonts/Silkscreen-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#00f0ff"
  adaptive_icon_foreground: "assets/logo.png"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#00f0ff"
    theme_color: "#00f0ff"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

